#!/bin/sh

# Connect to Inverter via BT
rfcomm connect rfcomm0 &

# set correct config for BT "serial port" connection
stty -F /dev/rfcomm0 1:0:cbd:0:3:1c:7f:15:1:10:0:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0 
